# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: https://cargocult.dev

# Localhost
# url: http://127.0.0.1:4000

title: Lovis Möller - Cargo Cult Programmer
description: Lovis from Hamburg writes about writing Software here. 
plainwhite:
  name: Lovis Möller
  tagline: CARGO CULT PROGRAMMER
  date_format: "%b %-d, %Y"

  social_links:
    twitter: lovisbrot
    github: lmller
    linkedIn:  # format: locale/username

show_excerpts: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
